### ISSUE TITLE
Avoid saving duplicate documents

### ISSUE THREAD

**Issue by flavioamieiro** [NAMD/pypln.web#11]
When saving a document, we need to first check if it is already in our gridfs and, if so, just point to it, instead of saving a new copy. With this we avoid not only extra disk space usage, but also processing the same document again to produce the same results.

**Comment by turicas** [comment]
There's a problem with this approach: if the user X uploads a document and then user Y uploads the same document, what will be the owner? If X deletes the file, it must remain in the database.
I think the better option will be changing `GridFSStorage` class at `pypln/web/apps/core/storage.py` to handle these problems (maybe checking the MD5 hash of the file).

**Comment by flavioamieiro** [comment]
@turicas I think that's the idea. 

I didn't explain it right, but the point is: once we have the document in GridFS, we should not store it again, and we should also not have to process it again.

The implementation details were not my concern when I created the issue, but I think you're right when you say GridFSStorage has this responsibilty.

**Comment by fccoelho** [comment]
Just for the record, since we have already discussed this offline: Documents must remain in the database for (at least) as long as there is a user associated with it, i.e., which "owns'' it or uses it in a corpus, Much like the way reference counting works in Python. However, I am willing to consider simply never deleting documents unless we run out of space, then we can apply the above heuristic.
