### ISSUE TITLE
Should support JSON-P and CORS

### ISSUE THREAD

**Issue by turicas** [NAMD/pypln.web#116]
To facilitate the usage of the API, it should support [JSON-P](https://en.wikipedia.org/wiki/JSONP) and [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing), this way anyone with a static site could consume its resources in JavaScript (without needing a backend dynamic server).

**Comment by fccoelho** [comment]
I Agree, though, for web calls we should place a size limit on the requests
in order to maintain a minimal speediness of reply

On Fri, Mar 28, 2014 at 10:36 PM, Álvaro Justen notifications@github.comwrote:

> To facilitate the usage of the API, it should support JSON-Phttps://en.wikipedia.org/wiki/JSONPand
> CORS https://en.wikipedia.org/wiki/Cross-origin_resource_sharing, this
> way anyone with a static site could consume its resources in JavaScript
> (without needing a backend dynamic server).
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/NAMD/pypln.web/issues/116
> .

## 

# Flávio Codeço Coelho

+55(21) 3799-5551
Professor
Escola de Matemática Aplicada
Fundação Getulio Vargas
Praia de Botafogo, 190 sala 312
Rio de Janeiro - RJ
22250-900
Brasil
