### ISSUE TITLE
Start a pypln.js library

### ISSUE THREAD

**Issue by fccoelho** [NAMD/pypln.web#20]
We should start a pypln.js library which will allow for performing som analysis on the client side.

Use cases:
- ephemeral analyses whose results are so specific that it make no sense to store permanently.
- Lighter analyses which may be done in realtime in the client. For example: ranking of words, and n-grams; building of custom graphs by the user, etc

This library will require a way to query the database (mongo), this may be done via an API with fixed queries or an authenticated proxy to the database for straight queries to be sent.

**Comment by turicas** [comment]
I'm closing this issue since it's not directly a feature request or a bug.
I can start thinking on a pypln.js library when we add a feature that can be implemented this way (like one ephemeral analysis that will run only on client side), but I don't see the needing for a issue addressing this right now.
