### ISSUE TITLE
Tests hang if backend is not running

### ISSUE THREAD

**Issue by flavioamieiro** [NAMD/pypln.web#25]
If we try to run the tests when the backend is not running, the tests hang forever. If it is not possible to run the tests without the backend (which should probably be the case), we need to at least stop the execution and warn the user about the problem.

**Comment by flavioamieiro** [comment]
This also probably points to an error in our application. We should be able to handle situations in which the backend is unavailable. The connection should at least time out.

Maybe in the long run we should use [Vaurien](https://vaurien.readthedocs.org/) to test the behavior of this frontend when the backend is unresponsive.

**Comment by flavioamieiro** [comment]
It appears to be the call to manager.start (which calls (get_api_reply)[https://github.com/NAMD/pypelinin/blob/develop/pypelinin/client.py#L58]) that hangs when the backend is not running. It is documented that this call without a call to send_api_request should hang, but maybe manager.start should detect that the router is not running.

@turicas any ideas?

**Comment by turicas** [comment]
I'll test some things here...but the problem is that with ZeroMQ we don't know when a connection or disconnection happens and API use request-reply sockets, so it needs to wait for a reply to finish the communication.

**Comment by flavioamieiro** [comment]
Isn't there a way to set a timeout for this connection?

**Comment by rhcarvalho** [comment]
This discussion made me remember this:

http://talks.golang.org/2012/concurrency.slide#47

Today the backend and web, although separate repos, must be running together, in perfect synchronism.
I haven't delve much deep into the code, but from the bugs I've found these days it seems that this old issue is still current.

Not just the tests from `web` depend on `backend`, as running `web` assumes there is a `backend` up and running somewhere.

If PyPLN is really something for the scale, I imagine running several instances of the backend in hundreds of servers... and everyday one or more of those servers will fail.

The patterns described in the Go talk I linked above seems to be must-haves.

---

BTW, is it possible to configure the `web` to talk to several `backends`? How to scale?!

**Comment by turicas** [comment]
@rhcarvalho, no! Actually `web` do not talk directly to `backend` -- it talks to one `router` and all the backends talk with `router`.

**Comment by rhcarvalho** [comment]
Hello!

My previous comment has two parts. @turicas, I believe you were addressing the second/bottom part about scaling, right?

My comment perhaps has a misuse of the term `backend`, because I had in mind different terminologies prior to @turicas explaining the pieces of "The Backend" (NAMD/pypln.backend repository) in an email on our mailing-list.

Whenever I said "backend" and "web" I meant generally the code hosted in each of those repositories.

Introducing a router to the story do not change the fact that, apparently, it is is still a current issue that the individual systems were not designed to handle exceptional cases of lack of connectivity.

I believe I am not saying anything new, just reinforcing what you guys already knew as I looked by this 2-month-old issue.

-- Let's get the systems to behave nicely! :-)

**Comment by turicas** [comment]
@rhcarvalho I liked the link you posted here and probably we can use this technique to create a more robust system, but I think in the future, not now -- and it should be made on top of [pypelinin](https://github.com/NAMD/pypelinin), not PyPLN.

**Comment by turicas** [comment]
We won't need to be worried about this when #90 is implemented since we won't need to communicate directly with backend anymore. I think we should maintain this issue openned only until #90 is not implemented (and close then we close), but we should not work on this problem.
