### ISSUE TITLE
 bad gateway error when uploading many documents

### ISSUE THREAD

**Issue by fccoelho** [NAMD/pypln.web#43]
I got a Bad Gateway error when I tried to upload 344 documents at once to a corpus.
I am not sure if this is related to pypln.web but I decided to report.

**Comment by flavioamieiro** [comment]
It probably is related. I'll see if it has to do with the size of the upload. Do you know the size for all the files together?

**Comment by fccoelho** [comment]
Not much, 2.1 MB

**Comment by flavioamieiro** [comment]
Ok, I've reproduced the bug here trying to upload 469 files. The problem was a timeout in the wsgi worker: 

```
2013-01-21 11:49:03 [15281] [CRITICAL] WORKER TIMEOUT (pid:15321)
```

This probably means our view is taking too long to process this many files (gunicorn's default timeout is 30 seconds, so it's taking a really long time!). I'll take a look at the view code to figure out why this is happening, but my guess is that the more than 300 synchronous calls to send_pipeline are to blame here.

**Comment by turicas** [comment]
Related to #48.

**Comment by turicas** [comment]
There are lots of improvements related to starting pipelines in [pypelinin 0.1.1](https://pypi.python.org/pypi/pypelinin/0.1.1) - I don't know if it can helps, but I think a benchmark sending lots of documents in only one POST request (with pypelinin 0.1.0 against 0.1.1) is worth it. I think it can be done based on [this benchmark](https://github.com/NAMD/pypelinin/tree/develop/benchmarks/optimize-PipelineManager) plus the creation of a method to add more than one document per request (currently, [pypln.api](https://github.com/NAMD/pypln.api) does not support it).

**Comment by flavioamieiro** [comment]
We need to verify if this is still happening after the rewrite.

**Comment by flavioamieiro** [comment]
We now only accept one document at a time, and this should not be an issue anymore.
