### ISSUE TITLE
Create cache for visualization views

### ISSUE THREAD

**Issue by flavioamieiro** [NAMD/pypln.web#54]
The visualizations are built every time we access the view. We should cache the result, since some calculations are intensive.

**Comment by turicas** [comment]
Maybe we can create "finalization" workers so **all** the processment will be made by pypelinin and the Web internet will just get data from MongoDB and send it through HTTP. It's the same as visualizations do not have the "controller" part, only "model" (getting properties from MongoDB) and "template" (HTML + CSS + JS to show it nicely).

**Comment by flavioamieiro** [comment]
That may be a good idea. Maybe we could have a visualization pipeline, that runs after the analytical pipeline finishes, but we have to be careful not to take much of the frontend logic into the backend. Specially since we have different visualizations for the same data (at least html/csv/txt, and json when we have a API). It's probably best to have all the processing in the backend (maybe with a 'visualization' pipeline) and the presentation (or layout) in the frontend.

**Comment by fccoelho** [comment]
I think all view should return immediately or almost immediately any processing that takes more than, say, 100ms, should be handed to a separate thread/process on the server and return a spinner. Then the spinner template sends ajax requests say, every second or so to check for completion of the task. In order to avoid a DOS-like problem when the "normal" traffic to the site increases, we can limit the number of background processes to a fixed number and use a queue to handle the visualizations. This can be accomplished easily with python queue module (from the standard library) or with something more sophisticated such as this:
http://django-utils.readthedocs.org/en/latest/django-utils/queue.html#module-djutils.queue.decorators
https://github.com/coleifer/django-utils

This way we maintain the logic of visualizations in the frontend but with no impact to the responsiveness of the views. But I am strongly in favor of caching results which will never change (there is no point in running it twice if it's going to yield the same result).
