### ISSUE TITLE
Translate the site into portuguese

### ISSUE THREAD

**Issue by fccoelho** [NAMD/pypln.web#6]
Give some other team members the pot files to translate. I am positive it can be done in a day.

**Comment by flavioamieiro** [comment]
It turns out most of the site is already translated into portuguese, but the configuration was not right, so it wasn't showing the translations to browsers that asked for it. f72d717fe9bd and 656a46fc29b27 fixed this, so the website is honoring the Accept-lang headers.

I'll now mark the strings that are not yet translated and upadate the messages file so we can have 100% of the text translated.

**Comment by rhcarvalho** [comment]
Hi, this Issue seems to be the big umbrella for specific parts missing translation now.
What about closing it?

**Comment by turicas** [comment]
@rhcarvalho, I agree. I think we should have little issues instead of umbrella ones.
