### ISSUE TITLE
Unfriendly login error message

### ISSUE THREAD

**Issue by rhcarvalho** [NAMD/pypln.web#74]
Trying to login with invalid credentials produces a user-unfriendly error message:

![Screen shot 2013-02-19 at 12 21 21 PM](https://f.cloud.github.com/assets/88819/170057/fa7296de-7a4b-11e2-9f54-7dfe1eef5533.png)
## 

I guess this has to do with how Pinax does things?

**Comment by rhcarvalho** [comment]
Oh... please somebody help me!

It seems that "INVALID_CONTEXT_VARIABLE" is only on my local server. The hosted instance running at http://demo.pypln.org did not show that, but this instead:

![Screen shot 2013-02-19 at 12 27 04 PM](https://f.cloud.github.com/assets/88819/170062/aa21e5e4-7a4c-11e2-893f-b574ff303f3f.png)

So I guess I am missing some local configuration? (I would consider this still a bug, perhaps a documentation bug...)

**Comment by flavioamieiro** [comment]
This happens because the Pinax bootstrap template expects a context variable that their login view does not define: `form_error_title`. The fact that `INVALID_CONTEXT_VARIABLE` shows up in development and not on production is expected. We define [TEMPLATE_STRING_IF_INVALID](https://docs.djangoproject.com/en/dev/ref/templates/api/#invalid-template-variables) in our development and test settings exactly to catch errors like this. In production, we fail silently if the variable is not found (django just replaces it with `''`).

For this specific case, I don't think we should fix this right now, since solving #70 would make it obsolete.
