### ISSUE TITLE
Word Cloud HTML view produces invalid HTML

### ISSUE THREAD

**Issue by rhcarvalho** [NAMD/pypln.web#76]
The word-cloud visualization produces HTML that only works when called via AJAX.

For a given document "trabalho_final.pdf":
http://demo.pypln.org/document/trabalho_final.pdf/visualization/word-cloud.html

Will produce HTML that misses basic structural tags and JS dependencies.

Seems that the page [/document/&lt;doc-slug&gt;#word-cloud](http://demo.pypln.org/document/trabalho_final.pdf#word-cloud) should actually consume data from a JSON source and create the word cloud with javascript.

**Comment by turicas** [comment]
I don't think it's a bug/problem since we use this generated HTML only on AJAX calls.
About creating in JavaScript: I'm totally against it, because:
- We'll need to write more JavaScript (which sucks for me ;)
- It can be slower to the client to get a JSON, transforms it in HTML rather than do it on the server
- We can't use Django template system to write the visualization template (this way we should do it in JavaScript)

@flavioamieiro, what do you think? Do you think it is really an issue?

**Comment by flavioamieiro** [comment]
I do think this is an issue, but I don't think this is the best time to solve it. Once we have a REST API, the backend will already generate json, and the web interface might as well consume that, or we can just have an entire page (with valid html) instead of a tab that includes partial html. 

In fact, I think we will need to restructure our visualizations once we restructure the way we serve information. In my opinion we should rely as little as possible on javascript. I think each visualization should have a url of their own, with an entire page, instead of just changing the `#` anchor and including partial html.

**Comment by rhcarvalho** [comment]
I opened this issue just as a reminder. I agree with @flavioamieiro that now is not the best time to change this alone: it is just a small piece of sand in the eye...

@flavioamieiro already described what I think about URLs -- I would expect "<doc>/viz/cloud" to be the link to the full page of cloud visualization for a given <doc>.
