### ISSUE TITLE
Documents uploaded when the backend is not available are never analyzed

### ISSUE THREAD

**Issue by rhcarvalho** [NAMD/pypln.web#78]
I've uploaded a document before having "pypln.backend" running.
The upload was OK, but after configuring and running the backend the document seems to never be processed, but the message on the web interface is:

![Screen shot 2013-02-20 at 2 04 28 PM](https://f.cloud.github.com/assets/88819/174704/87417b98-7b23-11e2-8f69-ede2a169209b.png)

**Comment by rhcarvalho** [comment]
This is related to #72 and #73, but stresses a different part of the problem.

Documents without any processing done should be automatically (re)inserted in the work queue.
There should be a way to know whether a "processing job" was complete, failed, etc...

**Comment by flavioamieiro** [comment]
Actually, I expected the upload not to work. I think it should hang indefinitely (in our infrastructure this would mean a "Bad gateway" message, since the wsgi process would timeout after 30 seconds) since [we call the backend synchronously to create the pipeline](https://github.com/NAMD/pypln.web/blob/develop/pypln/web/apps/utils/pipeline.py#L32). I could not reproduce a working upload with the backend unreachable. Can you reproduce this? If you can't this is probably an even worse bug, since the user will get a 'bad gateway' message.

There are a lot of issues with analysis not running (or being partially run). I think some of them would be solved by having a queue in the django infrastructure that does not depend on the backend running. This is a good example of it. If we have a queue in django (maybe in postgres) with the document id's still to be processed, then the frontend can accept uploads even if the backend is temporarily unreachable. Other issues involve #46, and probably means reading the jobs' exits status to be able to tell the user when there is an error in their analysis.
