### ISSUE TITLE
Avoid KeyError when there are no analysis ready for a document

### ISSUE THREAD

**Issue by flavioamieiro** [NAMD/pypln.web#99]
When a document has no analysis ready and someone tries to access it's '/properties/' page, the view raises a KeyError, because there are no properties for that document. We need to treat this error and tell the user what is happening.

**Comment by turicas** [comment]
If the document exists on PostgreSQL but not on MongoDB, I think the best response should be [HTTP 202 - Accepted](http://stackoverflow.com/questions/9794696/best-http-status-code-in-rest-api-for-not-ready-yet-try-again-later) with an empty JSON (or maybe with something like `{status: 'processing'}`), since the document exists but is not ready it.
I think this is the right approach since the user will receive a 2xx response (it will not generate and exception for him if he is using requests library, for example) and it won't generate an exception on the server.

**Comment by turicas** [comment]
Another good feature will be use the response headers on verb `HEAD` to retrieve the status of the document.
